var bar = svg.append("g")
   .attr("name", "bar")
   .attr("transform", "translate(0, 635)")

bar.append("g")
  .attr("name", "nuts2_labels")
  .selectAll("text")
  .data(nuts2)
  .enter()
  .append("text")
  .attr("x", 270)
  .attr("y", (d, i) => 20 + 40*(8-i))
  .attr("font-size", 24)
  .attr("text-anchor", "end")
  .text((d) => d.bl)

// bar plot
bar.append("g")
  .attr("name", "rects")
  .selectAll("rect")
  .data(nuts2)
  .enter()
  .append("rect")
  .attr("x", 300)
  .attr("y", (d, i) => 40*(8-i))
  .attr("height", 30)
  .attr("width", (d) => 700 * d.ratio/260)
  .attr("fill", (d) => d3.interpolateRdYlGn(1 - d.ratio/260))
  .attr("stroke-width", 1)
  .attr("stroke", "rgba(0,0,0,.4)")
  .on("mouseenter", (d) => {
    tooltip_map_update(d.bl, d.freq, d.pop, d.ratio)
    d3.selectAll("."+d.bl).transition()
      .attr("stroke-width", 5)
      color_legend.selectAll(".circle_"+d.bl).transition()
      .attr("r", 20).attr("opacity", .5).attr("stroke-width", 1)
  })
  .on("mouseleave", (d) => {
    d3.selectAll("."+d.bl).transition()
      .attr("stroke-width", 1)
      color_legend.selectAll(".circle_"+d.bl).transition()
      .attr("r", 10).attr("opacity", .7).attr("stroke-width", .5)
  })
  .attr("class", (d) => d.bl)

bar.append("g")
  .attr("name", "values")
  .selectAll("text")
  .data(nuts2)
  .enter()
  .append("text")
  .attr("x", (d) => 305 + 700 * d.ratio/260)
  .attr("y", (d, i) => 22 + 40*(8-i))
  .attr("font-size", 20)
  .text((d) => Math.round(d.ratio*10)/10)