

var color_legend = svg.append("g")
  .attr("name", "color_legend")
  .attr("transform", "translate(800, 555)")

color_legend.append("line")
  .attr("x1", x_linear(0))
  .attr("x2", x_linear(260))
  .attr("style", "stroke:rgba(0,0,0,.3);stroke-width:2")

color_legend.append("g")
  .attr("name", "circles")
  .selectAll("circle")
  //.data(data.features)
  //.data(Object.values(cases))
  .data(Object.keys(cases).map(key => cases[key]))
  //.data(cases2)
  .enter()
  .append("circle")
  //.attr("cx", (d) => x_linear(get_ratio(d)))
  .attr("cx", (d) => x_linear(d.ratio))
  .attr("r", 10)
  .attr("opacity", .7)
  //.attr("fill", (d) => get_color(get_ratio(d)))
  .attr("fill", (d) => get_color(d.ratio))
  .on("mouseover", handleMouseover)
  .on("mouseleave", handleMouseLeave)
  .attr("stroke-width", .5)
  .attr("stroke", "black")
  .attr("id", d => "circle_" + d.id )
  .attr("class", d => "circle_" + d.bl)
  //cases[d.properties.name].bl)
  //.attr("opacity", 0)
  //.transition()
  //.duration(1000)
  //.attr("opacity", 1)

var cl_values = color_legend.append("g").attr("name", "values")
  .attr("class", "ticks_ratio")

for (var i = 0; i <= 13; i++) {
    cl_values.append("text")
      .attr("x", x_linear(20*i))
      .attr("y", 60)
      .text(i*20)
}

color_legend.append("text")
  .attr("x", x_linear(260/2))
  .attr("y", 35)
  .text("Fälle pro 100.000 Einwohner")
  .attr("class", "ratio_xlab")
