var dot_plot = svg.append("g")
  .attr("name", "dot-plot")
  .attr("transform", "translate(0, 625)")

dot_plot.append("g")
  .attr("name", "lines")
  .selectAll("lines")
  .data(nuts2)
  .enter()
  .append("line")
  .attr("x1", x_log(5))
  .attr("x2", 890)
  .attr("y1", (d, i) => y_bl(i))
  .attr("y2", (d, i) => y_bl(i))
  .attr("style", "stroke:rgba(0,0,0,0.2);stroke-width:2")

function x_log(ratio) {
    if (ratio == 0)
    return(-100)
    return 340 + 190*(Math.log(ratio) - 2.9)
}

dot_plot.append("g")
  .selectAll("line")
  .data(nuts2)
  .enter()
  .append("line")
  .attr("x1", (d) => x_log(d.ratio_old))
  .attr("x2", (d) => x_log(d.ratio))
  .attr("y1", (d, i) => y_bl(i))
  .attr("y2", (d, i) => y_bl(i))
  .attr("class", (d) => d.bl)
  .attr("stroke", "rgba(0,0,0,0.5)")
  .attr("stroke-width", 4)

dot_plot.append("g")
  .attr("name", "points")
  .selectAll("circle")
  .data(nuts2)
  .enter()
  .append("circle")
  .attr("cx", (d) => x_log(d.ratio))
  .attr("cy", (d, i) => y_bl(i))
  .attr("r", 10)
  .attr("fill", "#6971e9")
  .attr("class", (d) => d.bl)
  .attr("stroke", "rgba(0,0,0,.4)")

dot_plot.append("g")
  .attr("name", "points")
  .selectAll("circle")
  .data(nuts2)
  .enter()
  .append("circle")
  .attr("cx", (d) => x_log(d.ratio_old))
  .attr("cy", (d, i) => y_bl(i))
  .attr("r", 10)
  .attr("fill", "#7621be")
  .attr("class", (d) => d.bl)
  .attr("stroke", "rgba(0,0,0,.4)")

dot_plot.append("g")
  .selectAll("circle")
  .data(nuts2)
  .enter()
  .append("text")
  .attr("x", (d) => x_log(d.ratio_old) - 20)
  .attr("y", (d, i) => y_bl(i))
  .attr("fill", "#7621be")
  .text((d) => Math.round(d.ratio_old*10)/10)
  .attr("text-anchor", "end")
  .attr("dominant-baseline", "central")
  .attr("font-size", 20)

dot_plot.append("g")
  .selectAll("circle")
  .data(nuts2)
  .enter()
  .append("text")
  .attr("x", d => x_log(d.ratio) + 20)
  .attr("y", (d, i) => y_bl(i))
  .attr("fill", "#6971e9")
  .text((d) => Math.round(d.ratio*10)/10)
  .attr("dominant-baseline", "central")
  .attr("font-size", 20)

var dot_plot_grid = dot_plot.append("g")

for (i = 0; i < 11; i++) {
    let x = [5, 7, 10, 14, 20, 30, 50, 70, 100, 140, 200][i]
    dot_plot_grid.append("line")
      .attr("x1", x_log(x))
      .attr("x2", x_log(x))
      .attr("y1", 0)
      .attr("y2", 40 + 40*8)
      .attr("style", "stroke:rgba(0,0,0,0.2);stroke-width:2")
      dot_plot_grid.append("text")
      .attr("x", x_log(x))
      .attr("y", -5)
      .text(x)
      .attr("text-anchor", "middle")
}

dot_plot.append("text")
  .attr("x", 500)
  .attr("y", -25)
  .text("Fälle pro 100.000 Einwohner (Logarithmiert)")
  .attr("text-anchor", "middle")
  .attr("font-weight", "bold")

dot_plot.append("g")
  .selectAll("text")
  .data(nuts2)
  .enter()
  .append("text")
  .attr("y", (d, i) => -5 + 20 + 40*(8-i))
  .attr("x", (d) => 0.5*(x_log(d.ratio) + x_log(d.ratio_old)))
  .attr("text-anchor", "middle")
  .text((d) => "+" +Math.round((d.ratio - d.ratio_old)/d.ratio_old*1000)/10 + "%")
  .attr("opacity", .7)

dot_plot.append("g")
  .selectAll("rect")
  .data(nuts2)
  .enter()
  .append("rect")
  .attr("x", d => x_log(d.ratio_old) - 70)
  .attr("width", d => x_log(d.ratio) - x_log(d.ratio_old) + 140)
  .attr("y", (d, i) => -20 + y_bl(i))
  .attr("height", 40)
  .attr("opacity", 0)
  .on("mouseenter", d => svg_highlight(d.bl))
  .on("mouseleave", d => svg_unhighlight(d.bl))


function dot_plot_highlight(bl) {
  dot_plot.selectAll("circle." + bl).transition()
    .attr("stroke-width", 5)
  dot_plot.selectAll("line." + bl).transition()
    .attr("stroke-width", 7)
}

function dot_plot_unhighlight(bl) {
  dot_plot.selectAll("circle." + bl).transition()
    .attr("stroke-width", 1)
  dot_plot.selectAll("line." + bl).transition()
    .attr("stroke-width", 4)
}