var dot_plot = svg.append("g")
  .attr("name", "dot-plot")
  .attr("transform", "translate(0, 625)")

let plot_order = {
    "Kärnten": 0, "Burgenland": 1, "Wien": 2, "Steiermark": 3, "Niederösterreich": 4, "Oberösterreich": 5,
    "Salzburg": 6, "Vorarlberg": 7, "Tirol": 8
}

dot_plot.append("g")
  .attr("name", "lines")
  .selectAll("lines")
  .data(nuts2)
  .enter()
  .append("line")
  .attr("x1", x_log(5))
  .attr("x2", 890)
  .attr("y1", (d, i) => y_bl(i))
  .attr("y2", (d, i) => y_bl(i))
  .attr("class", "grid")

function x_log(ratio) {
    if (ratio == 0)
    return(-100)
    return 340 + 190*(Math.log(ratio) - 2.9)
}

var nuts2_old = ts_data2.filter(d => d.Datum == "23.03")

dot_plot.append("g")
  .selectAll("line")
  .data(nuts2)
  .enter()
  .append("line")
  .attr("x1", (d, i) => x_log(nuts2_old[i].ratio))
  .attr("x2", d => x_log(d.ratio))
  .attr("y1", (d, i) => y_bl(i))
  .attr("y2", (d, i) => y_bl(i))
  .attr("class", d => d.bl + " connection_line")
  .attr("stroke", "rgba(0,0,0,0.5)")
  .attr("stroke-width", 7)

dot_plot.append("g")
  .attr("class", "ratio_new")
  .attr("name", "points")
  .selectAll("circle")
  .data(nuts2)
  .enter()
  .append("circle")
  .attr("cx", d => x_log(d.ratio))
  .attr("cy", (d, i) => y_bl(i))
  .attr("r", 10)
  .attr("class", d => d.bl)
  .classed("ratio_new", true)
  .attr("stroke", "rgba(0,0,0,.4)")

dot_plot.append("g")
  .attr("name", "points")
  .attr("class", "ratio_old")
  .selectAll("circle")
  .data(nuts2_old)
  .enter()
  .append("circle")
  .attr("cx", d => x_log(d.ratio))
  .attr("cy", (d, i) => y_bl(i))
  .attr("r", 10)
  .attr("class", d => d.bl)
  .classed("ratio_old", true)
  .attr("stroke", "rgba(0,0,0,.4)")

dot_plot.append("g")
  .attr("class", "ratio_old")
  .selectAll("text")
  .data(nuts2_old)
  .enter()
  .append("text")
  .attr("class", d => d.bl)
  .classed("ratio_value", true)
  .attr("x", (d, i) => x_log(d.ratio) - 20)
  .attr("y", (d, i) => y_bl(i))
  .text((d, i) => Math.round(d.ratio*10)/10)
  .attr("text-anchor", "end")
  .attr("dominant-baseline", "central")

dot_plot.append("g")
  .attr("class", "ratio_new")
  .selectAll("text")
  .data(nuts2)
  .enter()
  .append("text")
  .attr("class", d => d.bl)
  .classed("ratio_value", true)
  .attr("x", d => x_log(d.ratio) + 20)
  .attr("y", (d, i) => y_bl(i))
  .text(d => Math.round(d.ratio*10)/10)

var dot_plot_grid = dot_plot.append("g").attr("class", "ticks_ratio")

for (i = 0; i < 11; i++) {
    let x = [5, 7, 10, 14, 20, 30, 50, 70, 100, 140, 200][i]
    dot_plot_grid.append("line")
      .attr("x1", x_log(x))
      .attr("x2", x_log(x))
      .attr("y1", 0)
      .attr("y2", 40 + 40*8)
      .attr("class", "grid")
    dot_plot_grid.append("text")
      .attr("x", x_log(x))
      .attr("y", -5)
      .text(x)
      //.attr("text-anchor", "middle")
}

dot_plot.append("text")
  .attr("x", 500)
  .attr("y", -25)
  .text("Fälle pro 100.000 Einwohner (Logarithmiert)")
  .attr("class", "ratio_xlab")

dot_plot.append("g")
  .selectAll("text")
  .data(nuts2)
  .enter()
  .append("text")
  .attr("y", (d, i) => -5 + 20 + 40*(8-i))
  .attr("x", (d, i) => 0.5*(x_log(d.ratio) + x_log(nuts2_old[i].ratio)))
  .attr("text-anchor", "middle")
  .text((d, i) => "+" +Math.round((d.ratio - nuts2_old[i].ratio)/nuts2_old[i].ratio*1000)/10 + "%")
  .attr("opacity", .7)
  .attr("class", d => "percent_" + d.bl + " percent_value")

dot_plot.append("g")
  .selectAll("rect")
  .data(nuts2)
  .enter()
  .append("rect")
  .attr("x", (d, i) => x_log(nuts2_old[i].ratio) - 70)
  .attr("width", (d, i) => x_log(d.ratio) - x_log(nuts2_old[i].ratio) + 140)
  .attr("y", (d, i) => -20 + y_bl(i))
  .attr("height", 40)
  .attr("opacity", 0)
  .on("mouseenter", d => svg_highlight(d.bl))
  .on("mouseleave", d => svg_unhighlight(d.bl))


function dot_plot_highlight(bl) {
  dot_plot.selectAll("circle." + bl).transition().ease(d3.easeElastic).duration(1500)
    .attr("r", 13).attr("opactiy", 0.6)
  dot_plot.selectAll("line." + bl).transition().duration(500).ease(d3.easeLinear)
    .attr("stroke-width", 9)
  dot_plot.selectAll("." + bl).classed("highlighted", true)
  dot_plot.selectAll(".percent_" + bl).transition().duration(300).ease(d3.easeLinear)
    .attr("y", d => -7 + 20 + 40*(8-plot_order[d.bl]))
    .attr("font-size", 19)
}

function dot_plot_unhighlight(bl) {
  dot_plot.selectAll("circle." + bl).transition().duration(500)
    .attr("r", 10).attr("opactiy", 1)
  dot_plot.selectAll("line." + bl).transition().duration(500)
    .attr("stroke-width", 7)
  dot_plot.selectAll("." + bl).classed("highlighted", false)
  dot_plot.selectAll(".percent_" + bl).transition().duration(500)
    .attr("y", d => -5 + 20 + 40*(8 - plot_order[d.bl]))
    .attr("font-size", 17)
}

function dot_plot_update(difference) {
  let data_new = ts_data2.filter(d => d.difference == difference)
  let data_old = ts_data2.filter(d => d.difference == difference + 4)
  dot_plot.selectAll(".ratio_old").selectAll("circle")
    .data(data_old)
    .transition().ease(d3.easeElastic).duration(1000)
    .attr("cx", d => x_log(d.ratio))
  dot_plot.selectAll(".ratio_new").selectAll("circle")
    .data(data_new)
    .transition().ease(d3.easeElastic).duration(1000)
    .attr("cx", d => x_log(d.ratio))
  dot_plot.selectAll(".ratio_old").selectAll("text")
    .data(data_old)
    .transition().ease(d3.easeElastic).duration(1000)
    .attr("x", d => x_log(d.ratio) - 20)
    .text(d => Math.round(d.ratio*10)/10)
  dot_plot.selectAll(".ratio_new").selectAll("text")
    .data(data_new)
    .transition().ease(d3.easeElastic).duration(1000)
    .attr("x", d => x_log(d.ratio) + 20)
    .text(d => Math.round(d.ratio*10)/10)

  let old_ratio = i => data_old[i].ratio
  let new_ratio = i => data_new[i].ratio
  dot_plot.selectAll(".connection_line")
    .transition().ease(d3.easeElastic).duration(1000)
    .attr("x1", (d, i) => x_log(old_ratio(i)))
    .attr("x2", (d, i) => x_log(new_ratio(i)))

  dot_plot.selectAll(".percent_value")
    .transition().ease(d3.easeElastic).duration(1000)
    .attr("x", (d, i) => 0.5 * (x_log(old_ratio(i)) + x_log(new_ratio(i))) )
    .text((d, i) => "+" +Math.round((new_ratio(i) - old_ratio(i))/old_ratio(i)*1000)/10 + "%")
  dot_plot
    .selectAll("rect")
    .attr("x", (d, i) => x_log(old_ratio(i)) - 70)
    .attr("width", (d, i) => x_log(new_ratio(i)) - x_log(old_ratio(i)) + 140)
}